"""
Configuration module for Mutagen RAG system.
Centralizes all configuration constants, environment variables, and magic numbers.
"""
import os
from pathlib import Path

# ============================================================================
# Repository and Storage Configuration
# ============================================================================

# Get Mutagen repository path from environment variable or default
MUTAGEN_REPO_PATH = os.getenv(
    "MUTAGEN_REPO_PATH",
    "./Mutagen/Mutagen.Bethesda.Core"
)

# Storage path for vector index and metadata
STORAGE_PATH = "./storage"

# ChromaDB collection name
COLLECTION_NAME = "mutagen_handwritten_code"

# ============================================================================
# Code Splitting Configuration (for C# CodeSplitter)
# ============================================================================

# Number of lines per chunk (roughly)
CHUNK_LINES = 40

# Number of lines to overlap between chunks (maintains context)
CHUNK_OVERLAP_LINES = 15

# Maximum characters per chunk (safety limit)
MAX_CHARS = 2048

# ============================================================================
# Embedding Model Configuration
# ============================================================================

# HuggingFace embedding model for vector search
EMBEDDING_MODEL_NAME = "BAAI/bge-small-en-v1.5"

# ============================================================================
# Search Configuration
# ============================================================================

# Default number of results to return
DEFAULT_TOP_K = 10

# Multiplier for BM25 retriever candidate fetching
# Fetch more candidates for fusion (top_k * BM25_MULTIPLIER)
BM25_MULTIPLIER = 3

# Multiplier for vector retriever candidate fetching
# Fetch more candidates for fusion (top_k * VECTOR_MULTIPLIER)
VECTOR_MULTIPLIER = 2

# Reranker model name
RERANKER_MODEL_NAME = "BAAI/bge-reranker-base"

# Number of final results after reranking
# Should typically match or be less than top_k
RERANK_TOP_N_RATIO = 1.0  # Multiplier for top_k

# ============================================================================
# File Filtering Configuration
# ============================================================================

# File name suffixes that indicate generated files
GENERATED_SUFFIXES = [".g.cs", ".Autogen.cs", ".Generated.cs"]

# Directory names to exclude from scanning
EXCLUDED_DIRS = {"obj", "bin", "Generated", ".vs", ".git", "Autogenerated"}

# Content markers that indicate auto-generated files
GENERATED_MARKERS = [
    "<auto-generated>",
    "This code was generated",
    "// <auto-generated />",
    "Auto-generated code"
]

# Number of characters to check in file header for generated markers
HEADER_CHECK_CHARS = 1000

# ============================================================================
# Metadata Extraction Configuration
# ============================================================================

# Maximum length for joined types/methods string to avoid metadata overflow
MAX_METADATA_LENGTH = 500

# ============================================================================
# ChromaDB Configuration
# ============================================================================

# Default batch size for ChromaDB insertions (fallback)
DEFAULT_BATCH_SIZE = 2000

# Maximum batch size to consider
MAX_BATCH_SIZE = 5000

# Batch size divisor for safety margin
BATCH_SIZE_DIVISOR = 2

# ============================================================================
# Logging Configuration
# ============================================================================

# Default log file location (relative to repository root)
DEFAULT_LOG_FILE = "mcp_server.log"

# Log file maximum size (bytes)
LOG_MAX_BYTES = 2 * 1024 * 1024  # 2MB

# Number of log file backups to keep
LOG_BACKUP_COUNT = 3

# Log level
LOG_LEVEL = "INFO"
