"""
Test to reproduce the MCP tool call error with multiple paths.
This simulates how an AI client would call the refresh_index tool.
"""
import json
from server import mcp

def test_tool_schema():
    """Check the tool schema generated by FastMCP"""
    print("=" * 60)
    print("MCP Tool Schema Inspection")
    print("=" * 60)
    
    tools = mcp.get_tools()
    
    for tool in tools:
        if tool.name == "refresh_index":
            print(f"\nTool: {tool.name}")
            print(f"Description: {tool.description[:100]}...")
            print(f"\nInput Schema:")
            print(json.dumps(tool.inputSchema, indent=2, ensure_ascii=False))
            
            # Check if the schema allows string input
            properties = tool.inputSchema.get("properties", {})
            repo_paths_schema = properties.get("repo_paths", {})
            
            print(f"\nrepo_paths parameter:")
            print(f"  Type: {repo_paths_schema.get('type')}")
            print(f"  Default: {repo_paths_schema.get('default')}")
            
            return tool.inputSchema
    
    return None

def test_single_path_call():
    """Test calling refresh_index with a single path"""
    print("\n" + "=" * 60)
    print("Test 1: Single Path Call")
    print("=" * 60)
    
    from server import refresh_index
    
    # This should work
    result = refresh_index("./Mutagen")
    print(f"Result type: {type(result)}")
    print(f"Result (first 200 chars): {result[:200]}...")
    
def test_multi_path_call():
    """Test calling refresh_index with multiple paths (comma-separated)"""
    print("\n" + "=" * 60)
    print("Test 2: Multi-Path Call (Comma-Separated)")
    print("=" * 60)
    
    from server import refresh_index
    
    # This is what an AI would try to do
    multi_path = "./Mutagen,./NonExistent"
    print(f"Input: {multi_path}")
    print(f"Input type: {type(multi_path)}")
    
    result = refresh_index(multi_path)
    print(f"Result type: {type(result)}")
    print(f"Result (first 200 chars): {result[:200]}...")

def test_mcp_tool_call_simulation():
    """Simulate how MCP protocol would call the tool"""
    print("\n" + "=" * 60)
    print("Test 3: MCP Protocol Tool Call Simulation")
    print("=" * 60)
    
    # This simulates what happens when an AI client calls the tool
    # through the MCP protocol
    
    # Case 1: Single path as string
    print("\nCase 1: Single path")
    arguments = {"repo_paths": "./Mutagen"}
    print(f"Arguments: {json.dumps(arguments, ensure_ascii=False)}")
    
    from server import refresh_index
    result = refresh_index(**arguments)
    print(f"✓ Success: {result[:100]}...")
    
    # Case 2: Multiple paths as comma-separated string
    print("\nCase 2: Multiple paths (comma-separated)")
    arguments = {"repo_paths": "./Mutagen,./NonExistent"}
    print(f"Arguments: {json.dumps(arguments, ensure_ascii=False)}")
    
    result = refresh_index(**arguments)
    print(f"✓ Success: {result[:100]}...")
    
    # Case 3: What if AI passes an array instead?
    print("\nCase 3: Multiple paths as array (POTENTIAL ERROR)")
    try:
        # Some AI clients might try to pass an array
        arguments = {"repo_paths": ["./Mutagen", "./NonExistent"]}
        print(f"Arguments: {json.dumps(arguments, ensure_ascii=False)}")
        
        result = refresh_index(**arguments)
        print(f"✓ Success: {result[:100]}...")
    except TypeError as e:
        print(f"✗ ERROR: {e}")
        print("  → This is likely the issue! AI is passing array instead of string")

if __name__ == "__main__":
    try:
        # Test 1: Check tool schema
        schema = test_tool_schema()
        
        # Test 2: Single path call
        test_single_path_call()
        
        # Test 3: Multi-path call
        test_multi_path_call()
        
        # Test 4: MCP protocol simulation
        test_mcp_tool_call_simulation()
        
        print("\n" + "=" * 60)
        print("✅ All tests completed")
        print("=" * 60)
        
    except Exception as e:
        print(f"\n❌ Error during testing: {e}")
        import traceback
        traceback.print_exc()
