"""
Basic structure verification test for refactored modules.
Tests that modules can be imported and basic functionality works.
"""

def test_config():
    """Test config module imports and constants."""
    from config import (
        MUTAGEN_REPO_PATH,
        STORAGE_PATH,
        COLLECTION_NAME,
        CHUNK_LINES,
        CHUNK_OVERLAP_LINES,
        MAX_CHARS,
        GENERATED_SUFFIXES,
        EXCLUDED_DIRS
    )
    
    assert CHUNK_LINES == 40
    assert CHUNK_OVERLAP_LINES == 15
    assert MAX_CHARS == 2048
    assert ".g.cs" in GENERATED_SUFFIXES
    assert "obj" in EXCLUDED_DIRS
    print("✅ Config module OK")


def test_logging_config():
    """Test logging config module."""
    from logging_config import setup_logging, get_logger, REPO_ROOT
    from pathlib import Path
    
    assert REPO_ROOT == Path(__file__).resolve().parent
    
    # Test logger creation
    logger = get_logger("test")
    assert logger.name == "test"
    print("✅ Logging config module OK")


def test_file_filters():
    """Test file filtering classes."""
    from file_filters import FileFilterer
    from pathlib import Path
    
    filterer = FileFilterer()
    
    # Test fast filtering
    assert filterer.is_generated_file_fast(Path("test.g.cs")) == True
    assert filterer.is_generated_file_fast(Path("test.cs")) == False
    assert filterer.is_generated_file_fast(Path("obj/test.cs")) == True
    
    # Test header filtering
    assert filterer.is_header_generated("<auto-generated> content") == True
    assert filterer.is_header_generated("normal code") == False
    
    print("✅ File filters module OK")


def test_metadata_extractor():
    """Test metadata extraction."""
    from metadata_extractor import MetadataExtractor
    
    extractor = MetadataExtractor()
    
    test_code = """
    namespace Mutagen.Test
    {
        public class TestClass
        {
            public void TestMethod() {}
            private void PrivateMethod() {}
        }
    }
    """
    
    metadata = extractor.extract_all("test.cs", test_code)
    
    assert metadata.get("namespace") == "Mutagen.Test"
    assert "class:TestClass" in metadata.get("defined_types", "")
    assert "TestMethod" in metadata.get("methods", "")
    assert "PrivateMethod" not in metadata.get("methods", "")
    
    print("✅ Metadata extractor module OK")


def test_module_structure():
    """Test that all modules exist and have expected structure."""
    import config
    import logging_config
    import file_filters
    import metadata_extractor
    
    # Check config module has expected constants
    assert hasattr(config, 'MUTAGEN_REPO_PATH')
    assert hasattr(config, 'CHUNK_LINES')
    assert hasattr(config, 'EXCLUDED_DIRS')
    
    # Check logging_config has expected functions
    assert hasattr(logging_config, 'setup_logging')
    assert hasattr(logging_config, 'get_logger')
    
    # Check file_filters has FileFilterer class
    assert hasattr(file_filters, 'FileFilterer')
    
    # Check metadata_extractor has MetadataExtractor class
    assert hasattr(metadata_extractor, 'MetadataExtractor')
    
    print("✅ Module structure OK")


if __name__ == "__main__":
    print("Running refactoring verification tests...\n")
    
    try:
        test_config()
        test_logging_config()
        test_file_filters()
        test_metadata_extractor()
        test_module_structure()
        
        print("\n" + "="*50)
        print("✅ ALL TESTS PASSED")
        print("="*50)
        print("\nRefactoring verification successful!")
        print("- All modules import correctly")
        print("- Basic functionality works as expected")
        print("- Module structure is correct")
        
    except Exception as e:
        print(f"\n❌ TEST FAILED: {e}")
        import traceback
        traceback.print_exc()
        exit(1)
